
server:
  port: 8080
  servlet:
    application-display-name: gateway-server
    context-path: /gateway/
spring:
  application:
    name: gateway-server
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/server/eureka