server:
  port: 8080
  servlet:
    context-path: /gateway/
  
spring:
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
          
  application:
    name: gateway-server-example  
          
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

